version: "3.7"

services:
  php:
    build:
      context: ./
      dockerfile: ./Dockerfile
    container_name: myapp
    ports:
      - 80:80    
    restart: always
    depends_on:
      - mssql
    networks:
      - yakinnet
      
  mssql:
    image: mcr.microsoft.com/mssql/server:2022-preview-ubuntu-22.04
    container_name: mssqldb
    environment:
      - MSSQL_SA_PASSWORD=Un!q@to2023
      - ACCEPT_EULA=Y  
    ports:
      - 1433:1433
    networks:
      - yakinnet

networks:
  yakinnet:


